baseurl = "https://hypothetical.me/"
title = "Hypothetical Me"
languageCode = "en"

# pygmentsuseclasses = false # inject color codes instead of just css classes
# PygmentsCodeFences = true # highlight regular ```code```

buildDrafts = true
disableSitemap = true
enableRobotsTXT = true

[Params]
    desc = "YOLO2"
    author = "Ivan&nbsp;Vyshnevskyi"

[menu]
    [[menu.top]]
        name = "RSS"
        url = "/index.xml"
        identifier = "rss"
        weight = 100

    [[menu.bottom]]
        name = "Blog"
        url = "/"
        identifier = "index"
        weight = -100

    [[menu.bottom]]
        name = "RSS"
        url = "/index.xml"
        identifier = "rss"
        weight = 100
