baseurl = "https://hypothetical.me/"
title = "Hypothetical Me"
languageCode = "en-GB"
copyright = "© 2022 “Hypothetical Me” by Ivan Vyshnevskyi is licensed under a CC BY-SA 4.0 International License."

# pygmentsuseclasses = false # inject color codes instead of just css classes
# PygmentsCodeFences = true # highlight regular ```code```

enableRobotsTXT = false

disableHugoGeneratorInject = true

[author]
    name = "Ivan Vyshnevskyi"
    email = "ivan@hypothetical.me"
    profile = "https://vyshnevskyi.com"
    mastodon = "https://mastodon.social/@sainaen"

[Params]
    desc = "A blog about technology written by hypothetical, better version of me."
    github = "https://github.com/sainaen/hypothetical.me"

[menu]
    [[menu.top]]
        name = "RSS"
        url = "/index.xml"
        identifier = "rss"
        weight = 100

    [[menu.bottom]]
        name = "Blog"
        url = "/"
        identifier = "index"
        weight = -100

    [[menu.bottom]]
        name = "RSS"
        url = "/index.xml"
        identifier = "rss"
        weight = 100

[permalinks]
    post = "/post/:slug/"
    short = "/short/:slug/"

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true
